### ISSUE TITLE
Tracking Issue: Migration Guides

### ISSUE THREAD

**Issue by jordesign** [WordPress/data-liberation#2]
One of the [key aspects of the Data Liberation initiative](https://make.wordpress.org/core/2024/02/19/data-liberation-next-steps/) will be to have a set of Migration Guides that users can follow.

At their simplest - we'll be able to link to these guides to assist users prepare files for import. But there is hope that these may be able to be incorporated into tools that are being created.

This tracking issue is to list out all the Guides that are completed, in progress, or that we'd like to have. Feel free to propose additional guides in the comments.

## How can I contribute to the Guides?

If you'd like to add a new guide, or propose changes to another one, the best way is to create a Pull Request with the proposed changes. https://github.com/WordPress/data-liberation/tree/trunk/guides

## Guides

- [x] WordPress
- [x]  Tumblr
- [ ]  https://github.com/WordPress/data-liberation/issues/36
- [x]  WooCommerce products
- [ ]  https://github.com/WordPress/data-liberation/issues/34
- [ ]  https://github.com/WordPress/data-liberation/issues/35
- [ ]  https://github.com/WordPress/data-liberation/issues/37
- [ ]  https://github.com/WordPress/data-liberation/issues/38
- [ ]  https://github.com/WordPress/data-liberation/issues/40
- [ ]  https://github.com/WordPress/data-liberation/issues/41
- [ ]  https://github.com/WordPress/data-liberation/issues/42
- [ ]  https://github.com/WordPress/data-liberation/issues/43
- [ ]  https://github.com/WordPress/data-liberation/issues/44
- [x]  Kadence Blocks
- [ ]  https://github.com/WordPress/data-liberation/issues/45
- [ ] https://github.com/WordPress/data-liberation/issues/67
- [ ] https://github.com/WordPress/data-liberation/issues/65

**Comment by jordesign** [comment]
Updating this issue to add some additional proposed guides.

**Comment by nikolas4175-godaddy** [comment]
@jordesign would be great to see Webflow added to this list. Folks using that and similar "no-code" tools are a great target audience for this kind of work as they are most vulnerable to the whims of their current platforms and would benefit from a guided migration.
